name: "BioStart AR"
languages: ["es", "en"]

topics:
  tech: ["biotech", "genomics", "bioinformatics", "AI", "CRISPR", "bioprocess", "drug discovery"]
  finance: ["funding round", "Series A", "seed", "grant", "ANR", "FONCyT", "inversión", "ronda", "financiamiento"]
  academic: ["bioRxiv", "arXiv q-bio", "clinical trials"]

regions: ["AR", "US", "EU"]

watchlists:
  companies: ["Bioceres", "Inmunova", "mAbxience", "Bitgenia", "LUCAI"]

sources:
  rss:
    - "https://endpts.com/feed"                               # Endpoints (biotech global)
    - "https://www.agencia.mincyt.gob.ar/frontend/agencia/rss" # Agencia I+D+i (AR)
  html_pages:
    - page_url: "https://www.conicet.gov.ar/noticias-conicet/"
      link_selector:
        - "article a"
        - "h2 a"
        - "main a"
      limit: 6
      min_text_chars: 500
  apis:
    gdelt: false
    arxiv: true
    clinicaltrials: true

freshness_days: 14         
max_items: 20
max_items_per_section: 8

ranking:
  use_embeddings: true
  recency_half_life_days: 7
  domain_weights:
    "endpoints.news": 1.3
    "endpts.com": 1.3
    "fiercebiotech.com": 1.2
    "labiotech.eu": 1.2
    "conicet.gov.ar": 1.1         
    "agencia.mincyt.gob.ar": 1.2
    "argentina.gob.ar": 1.2
  boosts:
    argentina: 0.10
    funding: 0.10
    watchlist: 0.20

quality:
  min_text_chars: 350
  allow_short_sources: ["arxiv", "clinicaltrials", "rss", "html"]

critic:
  min_score_drop: 0.20     
  drop_paywall: "demote"   
  paywall_penalty: 0.10    
  drop_social: true
  drop_short_if_not_whitelisted: true
