name: "LUCAI.bio Watch"
languages: ["es", "en"]

topics:
  tech:
    - "bioinformatics"
    - "genomics"
    - "protein design"
    - "LLMs for biology"
    - "CRISPR"
    - "synthetic biology"
    - "metabolic engineering"
    - "bioprocess & fermentation"
    - "biosensors"
    - "green solvents"
    - "bioeconomy"
  finance:
    - "funding round"
    - "Series A"
    - "seed"
    - "grant"
    - "SOSV"
    - "GridX"
    - "QB3"
    - "IndieBio"
    - "ANR"
    - "FONCyT"
    - "inversión"
    - "financiamiento"
  academic:
    - "arXiv q-bio"
    - "bioRxiv"
    - "clinical trials"
    - "glycobiology"
    - "cyanobacteria"

regions: ["AR", "LatAm", "US", "EU"]

watchlists:
  companies:
    - "Dogma Biotech"
    - "Dogma"
    - "CyanoMin"
    - "Bioeutectics"

sources:
  rss:
    # Global biotech ya existentes
    - "https://endpts.com/feed"
    - "https://www.fiercebiotech.com/rss/xml"
    - "https://www.labiotech.eu/feed"
    # LatAm/AR
    - "https://latamlist.com/feed/"
    - "https://www.agencia.mincyt.gob.ar/frontend/agencia/rss"
    # NCBI (blog oficial - WordPress)
    - "https://ncbiinsights.ncbi.nlm.nih.gov/feed/"
    # Nature (biotech)
    - "http://feeds.nature.com/nbt/rss/current"               # Nature Biotechnology - Current issue
    - "https://www.nature.com/subjects/biotechnology.rss"     # Biotech a través de Nature Portfolio
    # Science (revista)
    - "https://www.science.org/action/showFeed?feed=rss&jc=stm&type=etoc"  # Sci Transl Med (biotech muy afín)
    # Bits in Bio (Substack)
    - "https://bitsinbio.substack.com/feed"
    # Forbes (ojo: solo biotech/health; si falla el RSS usar html_pages fallback)
    - "https://www.forbes.com/healthcare/index.xml"
    - "https://www.forbes.com/science/index.xml"

  html_pages:
    # ARCAP – el sitio no expone RSS moderno; scrapeamos la lista
    - page_url: "https://arcap.org/noticias-2/"
      link_selector:
        - "h2 a"
        - ".entry-title a"
        - "article a"
      limit: 6
      min_text_chars: 400
      verify_ssl: true

  apis:
    gdelt: false
    arxiv: true
    clinicaltrials: true
    pubmed:
      enabled: true
      query: '(biotechnology[MeSH Terms] OR "synthetic biology"[Title/Abstract] OR CRISPR[Title/Abstract] OR bioinformatics[Title/Abstract])'
      retmax: 20

freshness_days: 14
max_items: 30
max_items_per_section: 10

ranking:
  use_embeddings: true
  recency_half_life_days: 10
  domain_weights:
    "endpoints.news": 1.3
    "endpts.com": 1.3
    "fiercebiotech.com": 1.25
    "labiotech.eu": 1.25
    "latamlist.com": 1.2
    "agencia.mincyt.gob.ar": 1.25
    "conicet.gov.ar": 1.15
    "argentina.gob.ar": 1.2
    # Nuevos:
    "ncbiinsights.ncbi.nlm.nih.gov": 1.15
    "nature.com": 1.3
    "feeds.nature.com": 1.3
    "science.org": 1.25
    "bitsinbio.substack.com": 1.15
    "forbes.com": 1.05
  boosts:
    argentina: 0.15
    funding: 0.12
    watchlist: 0.30

quality:
  min_text_chars: 350
  allow_short_sources: ["arxiv", "clinicaltrials", "rss", "html"]

critic:
  min_score_drop: 0.10
  drop_paywall: "demote"
  paywall_penalty: 0.05
  drop_social: true
  drop_short_if_not_whitelisted: true

# Resumen automático con LLM (opcional)
llm_summary:
  enabled: true
  base_url: "http://localhost:9000/v1"
  api_key: "none"
  model: "local"
  lang: "es"
  bullets: 4
  max_tokens: 256
  temperature: 0.2
  chunk_chars: 2000
  timeout: 30
  min_chars: 0 