name: "LUCAI.bio Watch"
languages: ["es", "en"]

topics:
  tech:
    - "bioinformatics"
    - "genomics"
    - "protein design"
    - "LLMs for biology"
    - "CRISPR"
    - "synthetic biology"
    - "metabolic engineering"
    - "bioprocess & fermentation"
    - "biosensors"
    - "green solvents"
    - "bioeconomy"
  finance:
    - "funding round"
    - "Series A"
    - "seed"
    - "grant"
    - "SOSV"
    - "GridX"
    - "QB3"
    - "IndieBio"
    - "ANR"
    - "FONCyT"
    - "inversión"
    - "financiamiento"
  academic:
    - "arXiv q-bio"
    - "bioRxiv"
    - "clinical trials"
    - "glycobiology"
    - "cyanobacteria"

regions: ["AR", "LatAm", "US", "EU"]

watchlists:
  companies:
    - "Dogma Biotech"
    - "Dogma"          # alias
    - "CyanoMin"
    - "Bioeutectics"

sources:
  rss:
    - "https://endpts.com/feed"                       # Biotech global
    - "https://www.fiercebiotech.com/rss/xml"         # Biotech global (Fierce)
    - "https://www.labiotech.eu/feed"                 # Biotech EU
    - "https://latamlist.com/feed/"                   # VC/tech LatAm (financiamiento)
    - "https://www.bioeconomia.info/feed/"            # Bioeconomía en español (AR/LatAm)
    - "https://www.agencia.mincyt.gob.ar/frontend/agencia/rss"   # Agencia I+D+i (AR)
  html_pages:
    - page_url: "https://www.conicet.gov.ar/noticias-conicet/"
      link_selector:
        - "article a"
        - "h2 a"
        - "main a"
      limit: 8
      min_text_chars: 450
  apis:
    gdelt: false
    arxiv: true
    clinicaltrials: true

freshness_days: 14
max_items: 30
max_items_per_section: 10

ranking:
  use_embeddings: true
  recency_half_life_days: 10
  domain_weights:
    "endpoints.news": 1.3
    "endpts.com": 1.3
    "fiercebiotech.com": 1.25
    "labiotech.eu": 1.25
    "latamlist.com": 1.2
    "bioeconomia.info": 1.2
    "agencia.mincyt.gob.ar": 1.25
    "conicet.gov.ar": 1.15
    "argentina.gob.ar": 1.2
    "qb3.org": 1.1
  boosts:
    argentina: 0.15
    funding: 0.12
    watchlist: 0.30

quality:
  min_text_chars: 350
  allow_short_sources: ["arxiv", "clinicaltrials", "rss", "html"]

critic:
  min_score_drop: 0.10
  drop_paywall: "demote"
  paywall_penalty: 0.05
  drop_social: true
  drop_short_if_not_whitelisted: true
